name: DB Migrations

on:
  pull_request:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  db-migration-approval-flow:
    runs-on: ubuntu-latest
    # PR is either approved or created
    if: |
      (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') ||
      (github.event_name == 'pull_request')
    name: DB Migration
    steps:
      # Comment "checkout repo" before committing. Used only for local testing
      - name: checkout repo
        if: ${{ env.ACT }}
        uses: actions/checkout@v3

      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"


      - name: Approval check and migration run flow
        uses: varunnayal-org/database-migration-action@feature-github-only
        # ## Used "run" command for local testing
        # run: node db-migration-action/index.js
        with:
          repo-token: ${{ secrets.MIGRATION_GITHUB_TOKEN }} # custom repo token
          debug: ${{ env.DEBUG }} # defaults to false
