name: DB Migrations

on:
  issue_comment:       # dispatched when comment is added
    types: [created]
  repository_dispatch: # dispatched from JIRA comment
    types: [jira-comment-added]

jobs:
  db-migration-approval-flow:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/migrate')) ||
      (github.event_name == 'repository_dispatch' && github.event.client_payload.actionName == 'jira')
    name: DB Migration
    steps:
      # Comment "checkout repo" before committing. Used only for local testing
      - name: checkout repo
        if: ${{ env.ACT }}
        uses: actions/checkout@v3

      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"


      - name: Approval check and migration run flow
        uses: varunnayal-org/db-migration-action@feature-aws-jira-temp
        # ## Used "run" command for local testing
        # run: node db-migration-action/index.js
        with:
          repo-token: ${{ secrets.MIGRATION_GITHUB_TOKEN }} # custom repo token
          debug: ${{ env.DEBUG }} # defaults to false
          pr-base-branch: 'master'  # defaults to main
          # migration-config-file: './db.migration.json'
          approval-teams: "dba,data"
