name: DB Migrations

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  db-migration-approval-flow:
    runs-on: ubuntu-latest
    name: DB Migration
    steps:
      # # Uncomment this checkout if "node database-migration-action/dist/index.js" is used and you've checked out action in root dir
      # - name: checkout repo
      #   uses: actions/checkout@v3

      - name: Approval check and migration run flow
        uses: varunnayal-org/database-migration-action@feature-test
        # ## Used "run" command for local testing
        # run: node database-migration-action/dist/index.js
        env:
          DB_URL: ${{ vars.DB_URL }} # Change it to secrets later one
        with:
          repo_token: ${{ secrets.DB_MIGRATION_GITHUB_TOKEN }} # custom repo token
          db_migration_echo_url: ${{ vars.DB_MIGRATION_ECHO_URL }}
          debug: ${{ vars.DEBUG }} # defaults to false