name: DB Migrations

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  db-migration-approval-flow:
    runs-on: ubuntu-latest
    name: DB Migration
    steps:
      # # Uncomment this checkout if "node database-migration-action/dist/index.js" is used and you've checked out action in root dir
      # - name: checkout repo
      #   uses: actions/checkout@v3
      - name: Echo
        id: echo
        env:
          DB_MIGRATION_AWS_ACCESS_KEY_SECRET: dummy
        run: |
          echo DB_MIGRATION_AWS_ACCESS_KEY_SECRET: ${{ secrets.DB_MIGRATION_AWS_ACCESS_KEY_SECRET }}
          echo DB_MIGRATION_AWS_ACCESS_KEY_ID: ${{ secrets.DB_MIGRATION_AWS_ACCESS_KEY_ID }}
          echo DB_MIGRATION_AWS_ENDPOINT_URL: ${{ vars.DB_MIGRATION_AWS_ENDPOINT_URL }}
          echo DB_MIGRATION_AWS_REGION: ${{ vars.DB_MIGRATION_AWS_REGION }}
          echo DB_MIGRATION_GITHUB_TOKEN: ${{ secrets.DB_MIGRATION_GITHUB_TOKEN }}
          echo DB_MIGRATION_ECHO_URL: ${{ vars.DB_MIGRATION_ECHO_URL }}
          echo DB_MIGRATION_SECRET_STORE: ${{ vars.DB_MIGRATION_SECRET_STORE }}
          echo DEBUG: ${{ vars.DEBUG }}

      - name: Approval check and migration run flow
        uses: varunnayal-org/database-migration-action@feature-test
        # ## Used "run" command for local testing
        # run: node database-migration-action/dist/index.js
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DB_MIGRATION_AWS_ACCESS_KEY_SECRET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DB_MIGRATION_AWS_ACCESS_KEY_ID }}
          AWS_ENDPOINT_URL: ${{ vars.DB_MIGRATION_AWS_ENDPOINT_URL }}
          AWS_REGION: ${{ vars.DB_MIGRATION_AWS_REGION }}
        with:
          repo_token: ${{ secrets.DB_MIGRATION_GITHUB_TOKEN }} # custom repo token
          db_migration_echo_url: ${{ vars.DB_MIGRATION_ECHO_URL }} # TODO Change it to Secret
          aws_secret_store: ${{ vars.DB_MIGRATION_SECRET_STORE }} # TODO Change it to Secret
          debug: ${{ vars.DEBUG }} # defaults to false