# Generate github metadata file action.yml for generating db migrations
name: 'DB Migrations'
description: 'Run DB migrations'
branding:
  icon: 'database'
  color: 'purple'
inputs:
  repo_token:
    description: 'Github token'
    required: true
  migration_config_file:
    description: 'Migration configuration file'
    default: './db.migration.json'
  debug:
    description: 'show debug logs (true|false)'
    default: 'false'
  db_migration_echo_url:
    description: 'Echo github context and payload to URL'
    default: ''

runs:
  using: composite
  steps:
    # - name: Print GitHub Context
    #   shell: bash
    #   run: echo "${{ toJson(github) }}"
    # - name: LS
    #   shell: bash
    #   run: echo "${{ toJson(github) }}"

    - name: checkout repo for PR Events
      if: ${{ !(github.event_name == 'issue_comment' && github.event.issue.pull_request) }}
      uses: actions/checkout@v3

    - name: checkout repo for PR comment
      if: github.event_name == 'issue_comment' && github.event.issue.pull_request
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.issue.pull_request.head.ref }}

    - name: List Files
      shell: bash
      run: ls -ltrha

    # - name: migration approvals
    #   shell: bash
    #   run: node $GITHUB_ACTION_PATH/dist/index.js
    #   env:
    #     INPUT_REPO_TOKEN: ${{ inputs.repo_token }}
    #     INPUT_MIGRATION_CONFIG_FILE: ${{ inputs.migration_config_file }}
    #     INPUT_DEBUG: ${{ inputs.debug }}
    #     INPUT_DB_MIGRATION_ECHO_URL: ${{ inputs.db_migration_echo_url}}
