name: DB Migrations

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  db-migration-approval-flow:
    runs-on: ubuntu-latest
    # PR is either approved or created
    if: |
      (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') ||
      (github.event_name == 'pull_request')
    name: DB Migration
    steps:
      # Comment "checkout repo" before committing. Used only for local testing
      - name: checkout repo
        if: ${{ env.ACT }}
        uses: actions/checkout@v3

      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"

      - name: Print GitHub Env
        env:
          MIGRATION_GITHUB_TOKEN: ${{ secrets.MIGRATION_GITHUB_TOKEN }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        run: |
          env
          echo "\n\n"
          echo "MIGRATION_GITHUB_TOKEN: $MIGRATION_GITHUB_TOKEN"
          echo "AWS_ENDPOINT_URL: $AWS_ENDPOINT_URL"

      - name: Approval check and migration run flow
        uses: varunnayal-org/database-migration-action@feature-github-only
        # ## Used "run" command for local testing
        # run: node database-migration-action/dist/index.js
        with:
          repo_token: ${{ secrets.MIGRATION_GITHUB_TOKEN }} # custom repo token
          debug: ${{ env.DEBUG }} # defaults to false
          aws_access_key_id: 'dummy'
          aws_access_key_secret: 'dummy'
          aws_endpoint_url: ${{ secrets.AWS_ENDPOINT_URL }}
